# Generated by Django 4.2.11 on 2025-03-10 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Marca',
            new_name='Categoria',
        ),
    ]
