# Generated by Django 4.2.11 on 2025-03-10 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_rename_marca_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.BigIntegerField(unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('preco_custo', models.DecimalField(decimal_places=2, max_digits=7)),
                ('preco_venda', models.DecimalField(decimal_places=2, max_digits=7)),
                ('estoque', models.IntegerField()),
                ('data_cadastro', models.DateField(auto_now_add=True)),
                ('data_atualizacao', models.DateField(auto_now=True)),
                ('situacao', models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo')], max_length=20)),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.categoria')),
            ],
        ),
    ]
